version: '3'

services:
    ocr_back:
        build: ./back
        container_name: ocr_back
        ports:
            - 5000:80

    ocr_front:
        depends_on:
            - ocr_back
        build: ./front
        container_name: ocr_front
        ports:
            - 8000:80
