version: '3'

services:
    ocr_back:
        build: .
        container_name: ocr_demo
        ports:
            - 5000:80
#        volumes:
#            - ./app:/app

#    ocr_front:
#        depends_on:
#            - ocr_back
